<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookSwap.DataAccessLayer\BookSwap.DataAccessLayer.csproj" />
      <ProjectReference Include="..\BookSwap.Domain\BookSwap.Domain.csproj" />
    </ItemGroup>

</Project>
